project_name: copacetic
release:
  github:
    owner: sozercan
    name: copacetic
builds:
  - id: copacetic
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags: -s -w
      -X github.com/project-copacetic/copacetic/pkg/version.version={{.Version}}
      -X github.com/project-copacetic/copacetic/pkg/version.gitSHA={{.Commit}}
      -X github.com/project-copacetic/copacetic/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: copa
    hooks: {}

archives:
  - id: copacetic
    builds:
      - copacetic
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256


# DEFAULT_LDFLAGS   := -X $(BASE_PACKAGE_NAME)/pkg/version.GitCommit=$(GIT_COMMIT) \
#   -X $(BASE_PACKAGE_NAME)/pkg/version.GitVersion=$(GIT_VERSION) \
#   -X $(BASE_PACKAGE_NAME)/pkg/version.BuildDate=$(BUILD_DATE) \
  # -X main.version=$(CLI_VERSION)
