name: Publish release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - uses: anchore/sbom-action/download-syft@v0.14.0

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v4
        id: run-goreleaser
        with:
          version: latest
          args: release --clean --config .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release docs
        run: |
          TAG="$(echo "${{ github.ref }}" | tr -d 'refs/tags/v')"
          MAJOR_VERSION="$(echo "${TAG}" | cut -d '.' -f1)"
          MINOR_VERSION="$(echo "${TAG}" | cut -d '.' -f2)"
          CLI_VERSION=v${MAJOR_VERSION}.${MINOR_VERSION}.x make version-docs
